spring:
  application:
    name: Webflux-practice
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: h@sib2211
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/practice
#    username: postgres
#    password: h@sib2211
#  data:
#    r2dbc:
#      repositories:
#        enabled: true
#  flyway:
#    enabled: true
# JWT Secret (base64-encoded or plain string)
jwt:
  secret : Y2FzYW5vYmxlLXNlY3JldC1rZXktZm9yLWp3dC1oYTUxMi1hdXRoZW50aWNhdGlvbi1zeXN0ZW0tMjAyNQ==
  expiration : 3600000